# Generated by Django 4.2.6 on 2024-01-23 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productapp', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sid',
            field=models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.CASCADE, to='productapp.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
